// Configurazione SEO centralizzata: modifica QUI i valori (in primis `url`)
// e si aggiornano automaticamente metadati, sitemap, robots e dati strutturati.

export const siteConfig = {
  // IMPORTANTE: sostituisci con il dominio reale di produzione (senza slash finale).
  url: 'https://nicolasolazzo.com',
  name: 'Nicola Solazzo',
  title: 'Nicola Solazzo — Full Stack Developer & Consulente Web',
  description:
    'Consulente Full Stack per PMI e startup. Sviluppo di web app scalabili e performanti con React, Next.js e Node.js.',
  // Immagine social 1200x658 in JPEG (ottimizzata, ~244KB).
  ogImage: '/OG-image-card.jpg',
  locale: 'en_US',
  linkedin: 'https://www.linkedin.com/in/nicolasolazzo/',
  keywords: [
    'Nicola Solazzo',
    'Full Stack Developer',
    'Nuxt.js',
    'Vue.js',
    'Node.js',
    'Express.js',
    'TailwindCSS',
    'Bootstrap',
    'Material-UI',
    'SASS',
    'CSS3',
    'HTML5',
    'JavaScript',
    'TypeScript',
    'MongoDB',
    'MySQL',
    'PostgreSQL',
    'Firebase',
    'Supabase',
    'GraphQL',
    'Elixir',
    'Phoenix',
    'Python',
    'OpenAI',
    'Claude',
    'Codex',
    'Skills',
    'MCP',
    'Vibe Coding',
    'Agent AI',
    'Cursor',
    'VS Code',
    'Slack',
    'Monday',
    'Docker',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'GitLab',
    'REST API',
    'Consulente Web',
    'Sviluppo Web App',
  ],
} as const
